create table salesman(sno int primary key,sname varchar(50) not null,place varchar(50),pno varchar(10)unique);
create table saleorder(orno int primary key,ordate date not null,sno int references salesman(sno),del_type varchar(1),check(del_type in ('P','p','F','f')),ostatus varchar(25)check(ostatus in('inprocess','fulfilled','backorder','cancelled')));
insert into salesman values(100,'Noyal','Meloor','9876523110');
insert into salesman values(101,'Jeevan','Mala','8765231934');
insert into salesman values(102,'Aswin','Kollam','9876564444');
insert into salesman values(103,'Hari','Thrissur','9876544667');
insert into salesman values(104,'livin','pala','9876534433');
select * from salesman;
insert into saleorder values(1001,'11/2/2024','100','P','inprocess');
insert into saleorder values(1002,'22/3/2024','101','F','backorder');
insert into saleorder values(1003,'2/4/2024','102','p','cancelled');
insert into saleorder values(1004,'17/5/2024','103','f','fulfilled');
insert into saleorder values(1005,'10/6/2024','104','p','inprocess');
select * from saleorder;
alter table saleorder drop constraint saleorder_sno_fkey;
alter table salesman drop constraint salesman_pkey;
alter table saleorder drop constraint saleorder_del_type_check;
alter table salesman add primary key(sno);
alter table saleorder add foreign key(sno) references salesman(sno);
alter table saleorder add constraint del_type check(del_type in('p','P','f','F'));