create table b_cust(acc_no int primary key,c_name varchar(25),place varchar(25));
create table deposit(acc_no int references b_cust(acc_no),dno int primary key,damt int);
create table loan(acc_no int references b_cust(acc_no),lno int primary key,lamt int);
insert into b_cust values(1000,'hari','calicut');
insert into b_cust values(1001,'sushin','thrissur');
insert into b_cust values(1002,'aaron','malappuram');
insert into b_cust values(1003,'hela','kannur');
insert into b_cust values(1004,'logan','wayanad');
insert into b_cust values(1005,'krishna','kolla,');
select * from b_cust;
insert into deposit values(1000,3,250000);
insert into deposit values(1002,2,50000);
insert into deposit values(1002,4,80000);
update deposit set acc_no=1001 where dno=2;
select * from deposit;
insert into loan values(1004,1,250000);
insert into loan values(1005,3,150000);
insert into loan values(1002,4,40000);
select * from loan;
select distinct b_cust.acc_no,b_cust.c_name,deposit.damt from b_cust,deposit,loan where b_cust.acc_no=deposit.acc_no and deposit.acc_no not in(select loan.acc_no from loan);
select distinct b_cust.acc_no,b_cust.c_name,loan.lamt from b_cust,deposit,loan where b_cust.acc_no=loan.acc_no and loan.acc_no not in(select deposit.acc_no from deposit); 
select b_cust.acc_no,b_cust.c_name from b_cust,deposit,loan where b_cust.acc_no=deposit.acc_no and b_cust.acc_no=loan.acc_no;
select b_cust.acc_no,b_cust.c_name from b_cust where acc_no not in(select loan.acc_no from loan) and acc_no not in (select deposit.acc_no from deposit);